# Generated by Django 5.0.14 on 2026-08-02 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0002_initial_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock_alert',
            field=models.IntegerField(default=5),
        ),
    ]
