# Generated by Django 5.0.14 on 2026-05-31 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_user_email_unique'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['barber', 'date', 'start_time'], name='res_barber_date_start_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['client', 'is_deleted'], name='res_client_deleted_idx'),
        ),
    ]
