# Generated by Django 5.0.14 on 2026-07-13 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_barbershop_service_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ai_recommendations',
            field=models.BooleanField(default=True),
        ),
    ]
