# Generated by Django 5.0.14 on 2026-07-21 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_ai_recommendations'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='payment_intent_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
