# Generated by Django 5.0.14 on 2026-07-23 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_reservation_payment_intent_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='amount_paid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Espèces'), ('card', 'Carte')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='reservation',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Non payé'), ('paid_onsite', 'Payé au salon'), ('paid_online', 'Payé en ligne')], default='unpaid', max_length=20),
        ),
    ]
