# Generated by Django 5.0.14 on 2026-07-25 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_clientmedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientmedia',
            name='shared_with_client',
            field=models.BooleanField(default=False),
        ),
    ]
