# Generated by Django 5.0.14 on 2026-08-03 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_at_risk',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('confirmed', 'Confirmé'), ('cancelled', 'Annulé'), ('no_show', 'No-show')], default='pending', max_length=20),
        ),
    ]
