# Generated by Django 5.0.14 on 2026-08-03 17:49

import uuid

from django.db import migrations, models


def backfill_qr_code(apps, schema_editor):
    # Un default callable sur un champ unique n'est évalué qu'une seule fois par le
    # backend lors de l'ALTER TABLE — sur Postgres (prod Railway), toutes les
    # réservations existantes se retrouveraient avec le même UUID, ce qui viole la
    # contrainte unique dès qu'il y a plus d'une ligne. On peuple donc chaque ligne
    # individuellement ici, avant d'imposer la contrainte unique juste après.
    Reservation = apps.get_model('core', 'Reservation')
    for reservation in Reservation.objects.all():
        reservation.qr_code = uuid.uuid4()
        reservation.save(update_fields=['qr_code'])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_user_deleted_at_user_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='checked_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reservation',
            name='checked_in_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='qr_code',
            field=models.UUIDField(null=True, editable=False),
        ),
        migrations.RunPython(backfill_qr_code, noop),
        migrations.AlterField(
            model_name='reservation',
            name='qr_code',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
