# Generated by Django 5.0.14 on 2026-08-04 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_waitinglist'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarberLeave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barber', models.CharField(choices=[('Willo', 'Willo'), ('Malik', 'Malik'), ('Idris', 'Idris')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.CharField(blank=True, default='Congé', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['start_date'],
            },
        ),
    ]
