# Generated by Django 5.0.14 on 2026-08-08 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_add_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('confirmed', 'Confirmé'), ('cancelled', 'Annulé'), ('cancelled_client', 'Annulé par le client'), ('no_show', 'No-show')], default='pending', max_length=20),
        ),
    ]
