# Generated by Django 5.0.14 on 2026-08-08 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_reservation_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('rdv', 'Rendez-vous'), ('avis', 'Avis'), ('paiement', 'Paiement'), ('annulation', 'Annulation'), ('rappel', 'Rappel')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('desc', models.CharField(max_length=500)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
