# Generated by Django 5.0.14 on 2026-08-12 13:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='barbershop',
            name='commission_rate',
            field=models.DecimalField(decimal_places=1, default=4.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='user',
            name='two_factor_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_rdv_email', models.BooleanField(default=True)),
                ('new_rdv_sms', models.BooleanField(default=True)),
                ('new_rdv_push', models.BooleanField(default=True)),
                ('cancellation_email', models.BooleanField(default=True)),
                ('cancellation_sms', models.BooleanField(default=True)),
                ('cancellation_push', models.BooleanField(default=False)),
                ('new_review_email', models.BooleanField(default=True)),
                ('new_review_sms', models.BooleanField(default=False)),
                ('new_review_push', models.BooleanField(default=True)),
                ('daily_reminder_email', models.BooleanField(default=False)),
                ('daily_reminder_sms', models.BooleanField(default=True)),
                ('daily_reminder_push', models.BooleanField(default=True)),
                ('weekly_report_email', models.BooleanField(default=True)),
                ('weekly_report_sms', models.BooleanField(default=False)),
                ('weekly_report_push', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=20)),
                ('last4', models.CharField(max_length=4)),
                ('exp_month', models.IntegerField()),
                ('exp_year', models.IntegerField()),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_cards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_primary', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.CharField(blank=True, default='', max_length=255)),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
