# Generated by Django 5.0.14 on 2026-08-12 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_barbershop_commission_rate_user_two_factor_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='deletion_reason',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
